### EXPERIMENT 2: NUMERICAL PYTHON (NUMPY) <br> Submitted By: James, Kim Ezekiel G. | 2ECE-A | 09/05/2026

## A. REPRODUCIBLE NORMALIZATION PROBLEM
---
Create a reproducible random 5×5 integer ndarray named X. Use the following two statements before
performing any calculation:

`np.random.seed(2112)`<br>
`X = np.random.randint(10, 101, size=(5, 5))`

**Required checks:** Display X, X normalized, its mean, and its standard deviation. Up to floatingpoint rounding, the normalized mean must be 0 and the normalized standard deviation must be 1.
Save the normalized array as:
<br> `X_normalized.npy`

In [5]:
import numpy as np
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))

X_mean = X.mean()
O_std = X.std()

X_normalized = (X - X_mean) / O_std
print("X:")
print(X)

print("\nX_normalized:")
print(X_normalized)

print("\nMean of X_normalized:", X_normalized.mean())
print("Standard deviation of X_normalized:", X_normalized.std())

np.save("X_normalized.npy", X_normalized)

X:
[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

X_normalized:
[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

Mean of X_normalized: 0.0
Standard deviation of X_normalized: 0.9999999999999999


## B. CUBES DIVISIBLE BY 4 PROBLEM
---
Using NumPy, create the first 100 positive integers, cube every element, and reshape the result into a
10 × 10 ndarray named C. Thus, C begins with 1^3 and ends with 100^3
.
Use a Boolean condition on C to obtain every cubed value divisible by 4. Store the selected values in
div by 4. Preserve NumPy’s normal row-major selection order.

**Required checks:** Display the shape of C, the array div by 4, and the number of selected elements.
A correct solution has 50 selected elements; the first is 8 and the last is 1,000,000.
<br> Save the selected array as:
<br> `div_by_4.npy`

In [13]:
numbers = np.arange(1, 101)

C = numbers**3
C = C.reshape(10, 10)

div_by_4 = C[C % 4 == 0]

print("Shape of C:", C.shape)
print("\ndiv_by_4:")
print(div_by_4)

print("\nNumber of selected elements:", div_by_4.size)

np.save("div_by_4.npy", div_by_4)

Shape of C: (10, 10)

div_by_4:
[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

Number of selected elements: 50


## C. ABOVE-MEAN SQUARES PROBLEM
---
Create a 6 × 6 ndarray named S containing the squares of the first 36 positive integers in increasing
row-major order. Compute the mean of all elements of S and store it in S mean. Then use Boolean
filtering to select only the elements strictly greater than S mean. Store these values in above mean.
<br>**Required checks:** Display S, S mean, above mean, and the number of selected elements. A correct
solution has 15 selected elements; the first is 484 and the last is 1296.
<br> Save the selected array as:
<br> `above_mean.npy`

In [12]:
S = np.arange(1, 37)**2
S = S.reshape(6, 6)

S_mean = S.mean()
above_mean = S[S > S_mean]

print("S:")
print(S)
print("\nS_mean:", S_mean)

print("\nabove_mean:")
print(above_mean)

print("\nNumber of selected elements:", above_mean.size)

np.save("above_mean.npy", above_mean)

S:
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

S_mean: 450.1666666666667

above_mean:
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of selected elements: 15
